name: Build vim

on:
  workflow_dispatch:

jobs:
  setup:
    name: Build vim
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: vim/vim
      - run: dir /s *.exe
        shell: cmd
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0
      - run: |
          nmake -f Make_mvc.mak FEATURES=tiny
        working-directory: src
      - run: dir /s *.exe
        shell: cmd
