name: Build vim

on:
  workflow_dispatch:

jobs:
  setup:
    name: Build vim
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: mingw64
          pacboy: 'base-devel: toolchain:x'
      - uses: actions/checkout@v4
        with:
          repository: vim/vim
      - run: make -f Make_ming.mak
        working-directory: src
        shell: msys2 {0}
